config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :posts do
    end
  end

  resources :comments, only: [:create, :destroy]

  root to: "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  validates :author, presence: true, format: { with: /([A-Z][\w-]*(\s+[A-Z][\w-]*)+)/, message: "two words with capital letters" }
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true
  validates :content, presence: true

  mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category created."}
        format.js
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category updated."}
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end


  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:author, :content, :commentable_type, :commentable_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def new
    @category = Category.find(params[:category_id])
    @post = @category.posts.build
  end

  def edit
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @category, notice: "Post created." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post.category, notice: "Post updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post deleted."
    redirect_to @post.category
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :file, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div class="container">
  <div class="category-name"><strong><%= link_to category.name, category %></strong></div>
  <div class="category-description"><%= category.description %></div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Category name:" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description, "Category description:" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <%= form.submit action_name.humanize %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show", @category %> | 
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center">Categories</h1>
<div class="text-center"><%= link_to "Create Category", new_category_path, class: "btn btn-info" %></div>
<ul>
  <%= render @categories %>
</ul>

app/views/categories/new.html.erb
<div class="container">
  <h1 class="text-center">New Category</h1>
  <%= render "form", category: @category %>
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1><%= @category.name %></h1>
  <div><%= @category.description %></div>
  <div class="links">
    <%= link_to "Categories", categories_path %> | 
    <%= link_to "Edit Category", edit_category_path(@category) %> | 
    <%= link_to "Delete Category", @category, method: :delete %>
  </div>
  <br>
  <p><%= link_to "New Post", new_category_post_path(@category), class: "btn btn-info" %></p>
  <ul class="posts-list">
    <% @category.posts.each do |post| %>
      <li><%= link_to post.name, category_post_path(@category, post) %></li>
    <% end %>
  </ul>
  <br>
  <div class="comments">
    <%= render @category.comments if @category.comments.present? %>
  </div>
  <p><%= link_to "Add comment", "#", class: "add-comment" %></p>
  <%= render "comments/form", object: @comment = @category.comments.build %>
</div>

app/views/comments/_comment.html.erb
<div class="comment" data-comment-id="<%= comment.id %>">
  <strong class="comment-author"><%= comment.author %></strong>
  <p class="comment-date">
    <i><%= comment.created_at %> | <%= link_to "Delete", comment, method: :delete, remote: true %></i>
  </p>
  <p class="comment-content"><%= comment.content %></p>
</div>

app/views/comments/_form.html.erb
<div class="new-comment-form">
  <%= form_with(model: object) do |form| %>
    <div class="comment-errors"></div>

    <%= form.hidden_field :commentable_type, value: object.commentable_type %>
    <%= form.hidden_field :commentable_id, value: object.commentable_id %>

    <div class="form-group">
      <%= form.text_field :author, class: "form-control", placeholder: "Enter your name" %>
    </div>

    <div class="form-group">
      <%= form.text_field :content, class: "form-control"  %>
    </div>

    <%= form.submit "Add comment" %>
    
  <% end %>
</div>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  $(".new-comment-form").find(".comment-errors").append("Errors: <%= j @comment.errors.full_messages.join("; ") %>");
<% else %>
  $(".comments").append("<%= j render("comments/comment", comment: @comment) %>");
  $(".new-comment-form").hide();
  $(".new-comment-form").find("input[type='text']").val("");
  $(".new-comment-form").find(".comment-errors").text("");
<% end %>

app/views/comments/destroy.js.erb
$(".comments").find("[data-comment-id=<%= @comment.id %>]").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: [post.category, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Post name:" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, "Post content:" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :file, "Upload file:" %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <%= form.submit action_name.humanize %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Post</h1>
  
  <%= render "form", post: @post %>

  <%= link_to "Show", category_post_path(@post.category, @post) %> | 
  <%= link_to "Back", @post.category  %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center">New Post</h1>
  
  <%= render "form", post: @post %>

  <%= link_to "Back", @post.category %>
</div>

app/views/posts/show.html.erb
<div class="container  <%= controller_name %>-<%= action_name %>">
  <h1 class="text-center"><%= @post.name %></h1>
  <p><%= @post.content %></p>
  <p><%= link_to("Download file", @post.file.url) if @post.file? %></p>
  <p class="links">
    <%= link_to "Back", @post.category %> | 
    <%= link_to "Edit", edit_category_post_path(@post.category, @post) %> | 
    <%= link_to "Delete", category_post_path(@post.category, @post), method: :delete, data: {confirm: "Do you realy want to delete this post?"} %>
  </p>
  <div class="comments">
    <%= render @post.comments if @post.comments.present? %>
  </div>
  <p><%= link_to "Add comment", "#", class: "add-comment" %></p>
  <%= render "comments/form", object: @comment = @post.comments.build %>
</div>